import { Button, Tooltip } from '@mui/material';
import { Print as PrintIcon } from '@mui/icons-material';
import { useLanguage } from '../../context/LanguageContext';

const PrintButton = ({ data, title = 'Inventory Report' }) => {
  const { t } = useLanguage();

  const handlePrint = () => {
    if (!data || data.length === 0) return;

    const printWindow = window.open('', '_blank');
    
    let htmlContent = `
      <html>
        <head>
          <title>${title}</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              margin: 20px;
              color: #333;
            }
            h1 {
              text-align: center;
              color: #6366f1;
              border-bottom: 2px solid #6366f1;
              padding-bottom: 10px;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 20px;
            }
            th {
              background-color: #6366f1;
              color: white;
              padding: 12px;
              text-align: left;
              font-weight: bold;
              border: 1px solid #ddd;
            }
            td {
              padding: 10px;
              border: 1px solid #ddd;
            }
            tr:nth-child(even) {
              background-color: #f8fafc;
            }
            tr:hover {
              background-color: #f1f5f9;
            }
            .footer {
              margin-top: 30px;
              text-align: center;
              color: #94a3b8;
              font-size: 12px;
            }
            @media print {
              body {
                margin: 0;
              }
            }
          </style>
        </head>
        <body>
          <h1>${title}</h1>
          <p style="text-align: right; color: #64748b;">
            ${new Date().toLocaleString()}
          </p>
          <table>
            <thead>
              <tr>
                ${Object.keys(data[0])
                  .map(key => `<th>${key}</th>`)
                  .join('')}
              </tr>
            </thead>
            <tbody>
              ${data
                .map(
                  item =>
                    `<tr>
                      ${Object.values(item)
                        .map(value => `<td>${value || '-'}</td>`)
                        .join('')}
                    </tr>`
                )
                .join('')}
            </tbody>
          </table>
          <div class="footer">
            <p>Generated by Inventory Management System</p>
          </div>
        </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <Tooltip title={t('print') || 'Print'}>
      <Button
        variant="outlined"
        size="small"
        startIcon={<PrintIcon />}
        onClick={handlePrint}
        disabled={!data || data.length === 0}
      >
        {t('print') || 'Print'}
      </Button>
    </Tooltip>
  );
};

export default PrintButton;
