import { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage debe usarse dentro de LanguageProvider');
  }
  return context;
};

const translations = {
  es: {
    // Navigation
    dashboard: 'Panel de Control',
    inventory: 'Inventario',
    products: 'Productos',
    orders: 'Pedidos',
    suppliers: 'Proveedores',
    reports: 'Reportes',
    settings: 'Configuración',
    logout: 'Cerrar sesión',

    // Common
    search: 'Buscar',
    add: 'Agregar',
    edit: 'Editar',
    delete: 'Eliminar',
    save: 'Guardar',
    cancel: 'Cancelar',
    actions: 'Acciones',
    status: 'Estado',
    category: 'Categoría',
    quantity: 'Cantidad',
    price: 'Precio',
    cost: 'Costo',
    sku: 'Código',
    name: 'Nombre',
    description: 'Descripción',
    updatedAt: 'Actualizado',
    noInventoryItemsFound: 'No se encontraron artículos de inventario',
    startAddingItems: 'Comienza agregando tu primer artículo de inventario',
    editItem: 'Editar Artículo',
    updateItemDetails: 'Actualiza los detalles de tu artículo de inventario',
    addProductToInventory: 'Agrega un nuevo producto a tu inventario',
    supplier: 'Proveedor',
    minStock: 'Stock Mínimo',
    location: 'Ubicación',
    export: 'Exportar',
    print: 'Imprimir',
    allCategories: 'Todas las Categorías',

    // Inventory
    inventoryManagement: 'Gestión de Inventario',
    searchByNameOrSku: 'Buscar por nombre o código...',
    totalItems: 'Total de Artículos',
    productsInInventory: 'Productos en inventario',
    inventoryValue: 'Valor del Inventario',
    totalStockValue: 'Valor total del stock',
    lowStock: 'Stock Bajo',
    itemsNeedRestock: 'Artículos que necesitan reabastecimiento',
    outOfStock: 'Sin Stock',
    itemsUnavailable: 'Artículos no disponibles',
    inStock: 'En Stock',
    createNewItem: 'Crear Nuevo Artículo',
    confirmDelete: 'Confirmar Eliminación',
    areYouSure: '¿Estás seguro que deseas eliminar este artículo?',
    itemCreatedSuccessfully: 'Artículo creado exitosamente',
    itemUpdatedSuccessfully: 'Artículo actualizado exitosamente',
    itemDeletedSuccessfully: 'Artículo eliminado exitosamente',
    failedToCreateItem: 'Error al crear el artículo',
    failedToUpdateItem: 'Error al actualizar el artículo',
    failedToDeleteItem: 'Error al eliminar el artículo',
    bulkUpload: 'Carga masiva',
    loadInventory: 'Cargar Inventario',
    errorLoadingInventory: 'Error al cargar inventario',

    // Dashboard
    welcomeToDashboard: 'Bienvenido a tu panel de control de inventario',
    totalProducts: 'Total de Productos',
    categories: 'Categorías',
    categoriesInUse: 'Categorías en uso',
    activeSuppliers: 'Proveedores activos',
    monthlyRevenue: 'Ingresos mensuales',
    revenue: 'Ingresos',
    recentProducts: 'Productos Recientes',
    noDashboardData: 'Sin datos disponibles aún',
    errorLoadingData: 'Error al cargar datos',

    // Auth
    login: 'Iniciar sesión',
    email: 'Correo electrónico',
    password: 'Contraseña',
    rememberMe: 'Recuérdame',
    invalidCredentials: 'Usuario o contraseña incorrecta',
    loginFailed: 'Error al iniciar sesión',
    loginSuccessful: 'Sesión iniciada correctamente',
    forgotPassword: '¿Olvidaste tu contraseña?',
    inventoryManagementSystem: 'Sistema de Gestión de Inventario',
    emailAddress: 'Correo electrónico',
    loginButton: 'Iniciar sesión',
    welcomeBack: 'Bienvenido de vuelta',

    // Reports & Analytics
    reportsAnalytics: 'Reportes y Análisis',
    monitorInventory: 'Monitorea el rendimiento de tu inventario y métricas de ventas',
    exportReport: 'Exportar Reporte',
    quickRange: 'Rango Rápido',
    last7Days: 'Últimos 7 Días',
    last30Days: 'Últimos 30 Días',
    last90Days: 'Últimos 90 Días',
    lastYear: 'Último Año',
    granularity: 'Granularidad',
    hourly: 'Por Hora',
    weekly: 'Semanal',
    startDate: 'Fecha de Inicio',
    endDate: 'Fecha de Fin',
    totalRevenue: 'Ingresos Totales',
    currentPeriod: 'Período actual',
    totalOrders: 'Órdenes Totales',
    ordersPlaced: 'Órdenes realizadas',
    avgOrderValue: 'Valor Promedio de Orden',
    perTransaction: 'Por transacción',
    currentStock: 'Stock actual',
    salesTimeline: 'Timeline de Ventas',
    topProducts: 'Productos Principales',
    topSellingProducts: 'Productos Más Vendidos',
    categoryPerformance: 'Rendimiento de Categorías',
    inventoryStatus: 'Estado del Inventario',
    noDataAvailable: 'No hay datos disponibles',
    unitsSold: 'Unidades Vendidas',
    alerts: 'Alertas',
    calendar: 'Calendario',
    units: 'unidades',
    daily: 'Diario',
    monthly: 'Mensual',
    yearly: 'Anual',
    dateRange: 'Rango de fechas',
    sortBy: 'Ordenar por',
    order: 'Orden',

    // Stock Overview
    stockOverview: 'Resumen de Stock',
    viewStockAcrossWarehouses: 'Visualiza y gestiona el stock en todos los almacenes',
    totalStock: 'Stock Total',
    warehouse: 'Almacén',
    allWarehouses: 'Todos los Almacenes',
    stockLevel: 'Nivel de Stock',
    all: 'Todos',
    searchProducts: 'Buscar productos...',
    clearAll: 'Limpiar Todo',
    noProductsFound: 'No se encontraron productos',
    tryAdjustingFilters: 'Intenta ajustar los filtros',
    product: 'Producto',
    viewDetails: 'Ver Detalles',
    stockByWarehouse: 'Stock por Almacén',
    code: 'Código',
    stock: 'Stock',
    rowsPerPage: 'Filas por página:',
    critical: 'Crítico',
    low: 'Bajo',
    available: 'Disponible',
    exportFeatureComingSoon: 'Función de exportación próximamente',
    dataRefreshed: 'Datos actualizados',
    refresh: 'Actualizar',
    uniqueItems: 'Artículos únicos en sistema',
    unitsAvailable: 'Unidades disponibles',
    warehouses: 'Almacenes',
    activeLocations: 'Ubicaciones activas',
    lowStockItems: 'Stock Bajo',
    itemsNeedingAttention: 'Artículos que necesitan atención',
    occupancy: 'Ocupación',
    viewAll: 'Ver Todo',
    lowStockAlert: 'Alerta de Stock Bajo',
    manage: 'Gestionar',
    unitsLeft: 'unidades restantes',
    noLowStockItems: 'Todos los productos tienen stock suficiente',
    warehouseDashboard: 'Panel de Almacén',

    // Warehouses
    warehouseManagement: 'Gestión de Almacenes',
    manageWarehousesLocations: 'Administra tus almacenes y ubicaciones',
    addWarehouse: 'Agregar Almacén',
    editWarehouse: 'Editar Almacén',
    deleteWarehouse: 'Eliminar Almacén',
    totalWarehouses: 'Total de Almacenes',
    mainWarehouses: 'Almacenes Principales',
    searchWarehouses: 'Buscar almacenes por nombre, código o ciudad...',
    noWarehousesFound: 'No se encontraron almacenes',
    noWarehousesYet: 'Aún no hay almacenes',
    tryAdjustingSearch: 'Intenta ajustar tu búsqueda',
    startByAddingWarehouse: 'Comienza agregando tu primer almacén',
    contact: 'Contacto',
    manager: 'Responsable',
    mainWarehouse: 'Almacén Principal',
    notAssigned: 'No asignado',
    active: 'Activo',
    confirmDeleteWarehouse: '¿Estás seguro de eliminar el almacén',
    warehouseCreatedSuccessfully: 'Almacén creado exitosamente',
    warehouseUpdatedSuccessfully: 'Almacén actualizado exitosamente',
    warehouseDeletedSuccessfully: 'Almacén eliminado exitosamente',
    failedToCreateWarehouse: 'Error al crear almacén',
    failedToUpdateWarehouse: 'Error al actualizar almacén',
    failedToDeleteWarehouse: 'Error al eliminar almacén',
    basicInformation: 'Información Básica',
    locationInformation: 'Información de Ubicación',
    contactInformation: 'Información de Contacto',
    codeRequired: 'El código es requerido',
    nameRequired: 'El nombre es requerido',
    invalidEmail: 'Email inválido',
    warehouseNamePlaceholder: 'Almacén Central',
    warehouseDescriptionPlaceholder: 'Descripción del almacén...',
    addressPlaceholder: 'Calle Principal 123',
    cityPlaceholder: 'Ciudad',
    statePlaceholder: 'Estado',
    countryPlaceholder: 'País',
    managerNamePlaceholder: 'Nombre del responsable',
    mainWarehouseDescription: 'Marca este almacén como principal',
    zipCode: 'Código Postal',
    state: 'Estado/Provincia',
    country: 'País',
    phone: 'Teléfono',
    saving: 'Guardando...',
    update: 'Actualizar',
    create: 'Crear',
    address: 'Dirección',
    city: 'Ciudad',
    department: 'Departamento',
    selectCountry: 'Seleccione un país',
    selectDepartment: 'Seleccione un departamento',
    selectCity: 'Seleccione una ciudad',
    zipCodeOptional: 'Opcional',

    // Language
    language: 'Idioma',
    spanish: 'Español',
    english: 'English',
  },
  en: {
    // Navigation
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    products: 'Products',
    orders: 'Orders',
    suppliers: 'Suppliers',
    reports: 'Reports',
    settings: 'Settings',
    logout: 'Logout',

    // Common
    search: 'Search',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    actions: 'Actions',
    status: 'Status',
    category: 'Category',
    quantity: 'Quantity',
    price: 'Price',
    cost: 'Cost',
    sku: 'SKU',
    name: 'Name',
    description: 'Description',
    updatedAt: 'Updated',
    noInventoryItemsFound: 'No inventory items found',
    startAddingItems: 'Start by adding your first inventory item',
    editItem: 'Edit Item',
    updateItemDetails: 'Update the details of your inventory item',
    addProductToInventory: 'Add a new product to your inventory',
    supplier: 'Supplier',
    minStock: 'Minimum Stock',
    location: 'Location',
    export: 'Export',
    print: 'Print',
    allCategories: 'All Categories',

    // Inventory
    inventoryManagement: 'Inventory Management',
    searchByNameOrSku: 'Search by product name or SKU...',
    totalItems: 'Total Items',
    productsInInventory: 'Products in inventory',
    inventoryValue: 'Inventory Value',
    totalStockValue: 'Total stock value',
    lowStock: 'Low Stock',
    itemsNeedRestock: 'Items need restock',
    outOfStock: 'Out of Stock',
    itemsUnavailable: 'Items unavailable',
    inStock: 'In Stock',
    createNewItem: 'Create New Item',
    confirmDelete: 'Confirm Deletion',
    areYouSure: 'Are you sure you want to delete this item?',
    itemCreatedSuccessfully: 'Item created successfully',
    itemUpdatedSuccessfully: 'Item updated successfully',
    itemDeletedSuccessfully: 'Item deleted successfully',
    failedToCreateItem: 'Failed to create item',
    failedToUpdateItem: 'Failed to update item',
    failedToDeleteItem: 'Failed to delete item',
    bulkUpload: 'Bulk Upload',
    loadInventory: 'Load Inventory',
    errorLoadingInventory: 'Error loading inventory',

    // Dashboard
    welcomeToDashboard: 'Welcome to your inventory dashboard',
    totalProducts: 'Total Products',
    categories: 'Categories',
    categoriesInUse: 'Categories in use',
    activeSuppliers: 'Active suppliers',
    monthlyRevenue: 'Monthly revenue',
    revenue: 'Revenue',
    recentProducts: 'Recently Added Products',
    noDashboardData: 'No data available yet',
    errorLoadingData: 'Error loading data',

    // Auth
    login: 'Login',
    email: 'Email',
    password: 'Password',
    rememberMe: 'Remember me',
    invalidCredentials: 'Invalid email or password',
    loginFailed: 'Login failed',
    loginSuccessful: 'Login successful',
    forgotPassword: 'Forgot password?',
    inventoryManagementSystem: 'Inventory Management System',
    emailAddress: 'Email Address',
    loginButton: 'Login',
    welcomeBack: 'Welcome back',

    // Reports & Analytics
    reportsAnalytics: 'Reports & Analytics',
    monitorInventory: 'Monitor your inventory performance and sales metrics',
    exportReport: 'Export Report',
    quickRange: 'Quick Range',
    last7Days: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    last90Days: 'Last 90 Days',
    lastYear: 'Last Year',
    granularity: 'Granularity',
    hourly: 'Hourly',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    startDate: 'Start Date',
    endDate: 'End Date',
    totalRevenue: 'Total Revenue',
    currentPeriod: 'Current period',
    totalOrders: 'Total Orders',
    ordersPlaced: 'Orders placed',
    avgOrderValue: 'Avg Order Value',
    perTransaction: 'Per transaction',
    currentStock: 'Current stock',
    salesTimeline: 'Sales Timeline',
    topProducts: 'Top Products',
    topSellingProducts: 'Top Selling Products',
    categoryPerformance: 'Category Performance',
    inventoryStatus: 'Inventory Status',
    noDataAvailable: 'No data available',
    unitsSold: 'Units Sold',
    alerts: 'Alerts',
    calendar: 'Calendar',
    units: 'units',
    yearly: 'Yearly',
    dateRange: 'Date Range',
    sortBy: 'Sort By',
    order: 'Order',

    // Stock Overview
    stockOverview: 'Stock Overview',
    viewStockAcrossWarehouses: 'View and manage stock across all warehouses',
    totalStock: 'Total Stock',
    warehouse: 'Warehouse',
    allWarehouses: 'All Warehouses',
    stockLevel: 'Stock Level',
    all: 'All',
    searchProducts: 'Search products...',
    clearAll: 'Clear All',
    noProductsFound: 'No products found',
    tryAdjustingFilters: 'Try adjusting your filters',
    product: 'Product',
    viewDetails: 'View Details',
    stockByWarehouse: 'Stock by Warehouse',
    code: 'Code',
    stock: 'Stock',
    rowsPerPage: 'Rows per page:',
    critical: 'Critical',
    low: 'Low',
    available: 'Available',
    exportFeatureComingSoon: 'Export feature coming soon',
    dataRefreshed: 'Data refreshed',
    refresh: 'Refresh',
    uniqueItems: 'Unique items in system',
    unitsAvailable: 'Units available',
    warehouses: 'Warehouses',
    activeLocations: 'Active locations',
    lowStockItems: 'Low Stock',
    itemsNeedingAttention: 'Items needing attention',
    occupancy: 'Occupancy',
    viewAll: 'View All',
    lowStockAlert: 'Low Stock Alert',
    manage: 'Manage',
    unitsLeft: 'units left',
    noLowStockItems: 'All products are well stocked',
    warehouseDashboard: 'Warehouse Dashboard',

    // Warehouses
    warehouseManagement: 'Warehouse Management',
    manageWarehousesLocations: 'Manage your warehouses and locations',
    addWarehouse: 'Add Warehouse',
    editWarehouse: 'Edit Warehouse',
    deleteWarehouse: 'Delete Warehouse',
    totalWarehouses: 'Total Warehouses',
    mainWarehouses: 'Main Warehouses',
    searchWarehouses: 'Search warehouses by name, code or city...',
    noWarehousesFound: 'No warehouses found',
    noWarehousesYet: 'No warehouses yet',
    tryAdjustingSearch: 'Try adjusting your search',
    startByAddingWarehouse: 'Start by adding your first warehouse',
    contact: 'Contact',
    manager: 'Manager',
    mainWarehouse: 'Main Warehouse',
    notAssigned: 'Not assigned',
    active: 'Active',
    confirmDeleteWarehouse: 'Are you sure you want to delete warehouse',
    warehouseCreatedSuccessfully: 'Warehouse created successfully',
    warehouseUpdatedSuccessfully: 'Warehouse updated successfully',
    warehouseDeletedSuccessfully: 'Warehouse deleted successfully',
    failedToCreateWarehouse: 'Failed to create warehouse',
    failedToUpdateWarehouse: 'Failed to update warehouse',
    failedToDeleteWarehouse: 'Failed to delete warehouse',
    basicInformation: 'Basic Information',
    locationInformation: 'Location Information',
    contactInformation: 'Contact Information',
    codeRequired: 'Code is required',
    nameRequired: 'Name is required',
    invalidEmail: 'Invalid email',
    warehouseNamePlaceholder: 'Central Warehouse',
    warehouseDescriptionPlaceholder: 'Warehouse description...',
    addressPlaceholder: '123 Main Street',
    cityPlaceholder: 'City',
    statePlaceholder: 'State',
    countryPlaceholder: 'Country',
    managerNamePlaceholder: 'Manager name',
    mainWarehouseDescription: 'Mark this warehouse as main',
    zipCode: 'Zip Code',
    state: 'State/Province',
    country: 'Country',
    phone: 'Phone',
    saving: 'Saving...',
    update: 'Update',
    create: 'Create',
    address: 'Address',
    city: 'City',
    department: 'Department',
    selectCountry: 'Select a country',
    selectDepartment: 'Select a department',
    selectCity: 'Select a city',
    zipCodeOptional: 'Optional',

    // Language
    language: 'Language',
    spanish: 'Español',
    english: 'English',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Obtener idioma del localStorage o usar español por defecto
    return localStorage.getItem('language') || 'es';
  });

  useEffect(() => {
    // Guardar idioma en localStorage
    localStorage.setItem('language', language);
    // Actualizar lang del documento HTML
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.es[key] || key;
  };

  const toggleLanguage = () => {
    setLanguage(language === 'es' ? 'en' : 'es');
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};
